### ISSUE TITLE
cocoapods: circular dependency

### ISSUE THREAD

**Issue by djbe** [CyberAgent/iOS-NBUKit#17]
While updating cocoa pods today I noticed an issue with your framework, namely:

```
[!] There is a circular dependency between NBUKit/Library/NBUCompatibility and NBUKit/UI
```

Would it be possible for you to correct this? I think it'd just boil down to removing line #45:

```
sc.dependency       'NBUKit/UI'
```

from NBUCompatibility, as it isn't used elsewhere.

**Comment by riksof-abdulrauf** [comment]
guys we are facing the same issue, @djbe please tell us how can I solve it

**Comment by rivera-ernesto** [comment]
Just use the latest version.

**Comment by riksof-abdulrauf** [comment]
Thanks, it's fixed with removing the version number.
